### ISSUE TITLE
关于ysoserial.jar

### ISSUE THREAD

**Issue by d4wner** [sv3nbeast/ShiroScan#1]
老兄请教个问题，一般ysoserial.jar分为ysoserial.jar 和ysoserial-all.jar，一个一百多k，一个几十兆。
老兄研究过这两个有啥区别么，或者说在什么情况下小的那个可以代替？

**Comment by sv3nbeast** [comment]
我记不太清了，不过你要先看里面是否存在你要利用的类，有的话就可以使用，不过我没见过100多k的
![FP0`KS 5MPNYVJDY3XBIL%O](https://user-images.githubusercontent.com/55974091/68369405-33cb8a00-0175-11ea-8a9d-c8861f47225b.png)
![I9QZAI}4QM9VQ10`%@R)I3W](https://user-images.githubusercontent.com/55974091/68369410-37f7a780-0175-11ea-90e1-aac26c35ae0a.png)

**Comment by sv3nbeast** [comment]
![FP0`KS 5MPNYVJDY3XBIL%O](https://user-images.githubusercontent.com/55974091/68369445-4e9dfe80-0175-11ea-98ba-7a63a8bc3fe8.png)

**Comment by d4wner** [comment]
感谢答复，我回头反编译看看~
