### ISSUE TITLE
pip install -r requirement.txt failed

### ISSUE THREAD

**Issue by dbj1216** [sv3nbeast/ShiroScan#2]
前辈，你的requirement里面的依赖是咋弄来的，升级了pip，换了镜像源都不行，请赐教！

**Comment by sv3nbeast** [comment]
我记着当时是单独去官网下载的依赖，单独安装的，然后按报错照着google搜的然后解决的

**Comment by dbj1216** [comment]
> 我记着当时是单独去官网下载的依赖，单独安装的，然后按报错照着google搜的然后解决的

![image](https://user-images.githubusercontent.com/32815348/79875233-f2c1ec00-841b-11ea-963d-c600ff7fe773.png)
太神奇了。。不知道是不是我本地环境问题
