### ISSUE TITLE
对使用https的网站出现 以下报错。。 请大神指点迷津

### ISSUE THREAD

**Issue by bearOwang** [sv3nbeast/ShiroScan#4]
HTTPSConnectionPool(host='xxx.xx.xxx.xxx', port=xxx): Max retries exceeded with url:/login (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

**Comment by sv3nbeast** [comment]
这个应该是目标网站的机制，脚本请求速度过快，他拒绝连接，我觉得是哈，也不确定
