### ISSUE TITLE
是不是不能对https的网站进行检测

### ISSUE THREAD

**Issue by ppu-zengxin** [sv3nbeast/ShiroScan#5]
HTTPSConnectionPool(host='xx.xx.xx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
HTTPSConnectionPool(host='xx.xx.xx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
HTTPSConnectionPool(host='xx.xx.xx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
HTTPSConnectionPool(host='xx.xx.xx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
HTTPSConnectionPool(host='xx.xx.xx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
HTTPSConnectionPool(host='xx.xx.xx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

**Comment by sv3nbeast** [comment]
可以对https进行检测，比如你对百度进行检测

**Comment by ppu-zengxin** [comment]
> 可以对https进行检测，比如你对百度进行检测

大佬，你看我那个报错信息。百度的https可以扫可能是因为百度http也能访问到。我要扫的这个站只有https，如果访问http是默认页面，可能是因此访问不到。因为是公司的站，所以不能发给大佬测试，请见谅。

**Comment by 1in9e** [comment]
ssl证书有问题的站会报错，可以试试把构造好的rememberMe通过burp发过去。

**Comment by sv3nbeast** [comment]
已修复对https检测时出现的报错信息，请git同步下，感谢提出的issue，如果还有问题欢迎继续开启新的issue

**Comment by ppu-zengxin** [comment]
大佬还是强，膜拜
