### ISSUE TITLE
安装依赖包报错

### ISSUE THREAD

**Issue by inotgaoshou** [sv3nbeast/ShiroScan#8]
pip3 install -r requirments.txt
ERROR: Could not find a version that satisfies the requirement os (from -r requirments.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for os (from -r requirments.txt (line 1))

**Comment by Westbrookadmin** [comment]
> pip3 install -r requirments.txt
> ERROR: Could not find a version that satisfies the requirement os (from -r requirments.txt (line 1)) (from versions: none)
> ERROR: No matching distribution found for os (from -r requirments.txt (line 1))
hello，try running the following command：
pip uninstall crypto pycryptodome
pip install pycryptodome
